host-server/config/routes.rb
Rails.application.routes.draw do
  resources :conferences
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

host-server/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

host-server/app/models/conference.rb
class Conference < ApplicationRecord
  has_one_attached :backpath
end

host-server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

host-server/app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  http_basic_authenticate_with name: ENV['HOST_USER'], password: ENV['HOST_PASS'] if ENV['HOST_USER']
  before_action :set_conference, only: [:show, :edit, :update, :destroy]

  # GET /conferences
  # GET /conferences.json
  def index
    @conferences = Conference.all
  end

  # GET /conferences/1
  # GET /conferences/1.json
  def show
  end

  # GET /conferences/new
  def new
    @conference = Conference.new
  end

  # GET /conferences/1/edit
  def edit
  end

  # POST /conferences
  # POST /conferences.json
  def create
    @conference = Conference.new(conference_params)

    respond_to do |format|
      if @conference.save
        format.html { redirect_to @conference, notice: 'Conference was successfully created.' }
        format.json { render :show, status: :created, location: @conference }
      else
        format.html { render :new }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conferences/1
  # PATCH/PUT /conferences/1.json
  def update
    respond_to do |format|
      if @conference.update(conference_params)
        format.html { redirect_to @conference, notice: 'Conference was successfully updated.' }
        format.json { render :show, status: :ok, location: @conference }
      else
        format.html { render :edit }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conferences/1
  # DELETE /conferences/1.json
  def destroy
    @conference.destroy
    respond_to do |format|
      format.html { redirect_to conferences_url, notice: 'Conference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conference
      @conference = Conference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conference_params
      params.require(:conference).permit(:description, :password, :bankpath, :zip)
    end
end

host-server/app/helpers/application_helper.rb
module ApplicationHelper
end

host-server/app/helpers/conferences_helper.rb
module ConferencesHelper
end

host-server/app/views/conferences/_form.html.erb
<%= form_with(model: conference, local: true) do |form| %>
  <% if conference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conference.errors.count, "error") %> prohibited this conference from being saved:</h2>

      <ul>
      <% conference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :bankpath %>
    <%= form.file_field :bankpath %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

host-server/app/views/conferences/edit.html.erb
<h1>Editing Conference</h1>

<%= render 'form', conference: @conference %>

<%= link_to 'Show', @conference %> |
<%= link_to 'Back', conferences_path %>

host-server/app/views/conferences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Conferences</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Password</th>
      <th>Bankpath</th>
      <th>Zip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conferences.each do |conference| %>
      <tr>
        <td><%= conference.description %></td>
        <td><%= conference.password %></td>
        <td><%= conference.bankpath.url %></td>
        <td><%= conference.zip %></td>
        <td><%= link_to 'Show', conference %></td>
        <td><%= link_to 'Edit', edit_conference_path(conference) %></td>
        <td><%= link_to 'Destroy', conference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conference', new_conference_path %>

host-server/app/views/conferences/new.html.erb
<h1>New Conference</h1>

<%= render 'form', conference: @conference %>

<%= link_to 'Back', conferences_path %>

host-server/app/views/conferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @conference.description %>
</p>

<p>
  <strong>Password:</strong>
  <%= @conference.password %>
</p>

<p>
  <strong>Bankpath:</strong>
  <%= @conference.bankpath %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @conference.zip %>
</p>

<%= link_to 'Edit', edit_conference_path(@conference) %> |
<%= link_to 'Back', conferences_path %>

host-server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HostServer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>